<?php
$erreur = false;

$action = (isset($_POST['action'])? $_POST['action']:  (isset($_GET['action'])? $_GET['action']:null )) ;
if($action !== null)
{
   if(!in_array($action,array('ajout', 'suppression', 'refresh')))
   $erreur=true;

   //récuperation des variables en POST ou GET
   $l = (isset($_POST['l'])? $_POST['l']:  (isset($_GET['l'])? $_GET['l']:null )) ;
   $p = (isset($_POST['p'])? $_POST['p']:  (isset($_GET['p'])? $_GET['p']:null )) ;
   $q = (isset($_POST['q'])? $_POST['q']:  (isset($_GET['q'])? $_GET['q']:null )) ;

   //Suppression des espaces verticaux
   $l = preg_replace('#\v#', '',$l);
   //On verifie que $p soit un float
   $p = floatval($p);

   //On traite $q qui peut etre un entier simple ou un tableau d'entier
    
   if (is_array($q)){
      $QteArticle = array();
      $i=0;
      foreach ($q as $contenu){
         $QteArticle[$i++] = intval($contenu);
      }
   }
   else
   $q = intval($q);
    
}

if (!$erreur){
   switch($action){
      Case "ajout":
         ajouterArticle($l,$q,$p);
         break;

      Case "suppression":
         supprimerArticle($l);
         break;

      Case "refresh" :
         for ($i = 0 ; $i < count($QteArticle) ; $i++)
         {
            modifierQTeArticle($_SESSION['panier']['libelleProduit'][$i],round($QteArticle[$i]));
         }
         break;

      Default:
         break;
   }
}
?>
<!--COMMANDE-->

<form class="generic-form">
<h2><i class="fa fa-shopping-cart"></i> Passer une commande</h2>

<!--AJOUT-->
<fieldset action="#" method="post">
    <legend> Ajouter une article</legend>

<ul>
<!--SELECTION PRODUITS-->
	<li><label for="add">Nom: </label>

		<select id="add" name="add" /> 
            <?php foreach($meals as $meal): ?>
				<option><?= $meal['Name']; ?></option>
        	<?php endforeach; ?>       	
        </select>
    </li>

<!--AFFICHAGE PRODUIT-->
	<li><label for="basket-product"></label>
		<fieldset id="basket-product">
			<img src="<?= $wwwUrl ?>/images/meals/<?= $meal['Photo']; ?>">
			<p><?= $meal['Name']; ?></p>
			<p><?= $meal['Description']; ?></p>		
		</fieldset>
    </li>

<!--QUANTITE-->
    <li><label for="quantity">Quantité: </label>
    	<input type="number" name="quantity">  	
    </li>

<!--BOUTONS-->
    <a href="<?= $requestUrl ?>/order?action=ajout&amp;l=LIBELLEPRODUIT&amp;q=QUANTITEPRODUIT&amp;p=PRIXPRODUIT"; return false;"><button class="button-primary button" name="addproduct">Ajouter</button></a>

</ul>
</fieldset>

<!--BASKET-->
<fieldset>
	<legend> Recapitulatif de la commande</legend>

	<!--Basket plein-->
		
				<?php
					if (creationPanier()){

						$nbArticles=count($_SESSION['panier']['libelleProduit']);

						if ($nbArticles <= 0)
						echo "<tr><td>Votre panier est vide </ td></tr>";

						else{
							echo "<table>
									<thead>
										<tr>
										<th>Quantité</th>
										<th>Produit</th>
										<th>Prix Unitaire</th>
										<th>Prix Total</th>
										<th></th>
										</tr>
									</thead>
									<tbody>";

							for ($i=0 ;$i < $nbArticles ; $i++){

								echo "<tr>";
								echo "<td>".htmlspecialchars($_SESSION['panier']['libelleProduit'][$i])."</ td>";
								echo "<td><input type=\"text\" size=\"4\" name=\"q[]\" value=\"".htmlspecialchars($_SESSION['panier']['qteProduit'][$i])."\"/></td>";
								echo "<td>".htmlspecialchars($_SESSION['panier']['prixProduit'][$i])."</td>";
								echo "<td><a href=\"".htmlspecialchars("panier.php?action=suppression&l=".rawurlencode($_SESSION['panier']['libelleProduit'][$i]))."\">XX</a></td>";
								echo "</tr>";
							}

						echo "<tr><td colspan=\"2\"> </td>";
						echo "<td colspan=\"2\">";
						echo "Total : ".MontantGlobal();
						echo "</td></tr>";

						echo "<tr><td colspan=\"4\">";
						echo "<input type=\"submit\" value=\"Rafraichir\"/>";
						echo "<input type=\"hidden\" name=\"action\" value=\"refresh\"/>";
						echo "</td></tr>";
						}
					}
					?>
			</tbody>
		</table>
</fieldset>

<!--BOUTONS-->
    <input class="button-primary button" type="submit" name="" value="Valider la commande">
    <input class="button-cancel button" type="reset" name="" value="Annuler">

<script src="../js/classes/OrderForm.class.js"></script>