<!--COMMANDE-->
<form class="generic-form">
<h2><i class="fa fa-shopping-cart"></i> Passer une commande</h2>

<!--AJOUT-->
<fieldset action="#" method="post">
    <legend> Ajouter une article</legend>

<ul>
<!--SELECTION PRODUITS-->
	<li><label for="add">Nom: </label>

		<select id="add" name="add"/> 
            <?php foreach($meals as $meal): ?>
				<option value="<?= $meal['Id']; ?>" onclick="selectItem(event);"><?= $meal['Name']; ?></option>
        	<?php endforeach; ?>       	
        </select>
    </li>

<!--AFFICHAGE PRODUIT-->
	<li><label for="basket-product"></label>
		<fieldset id="basket-product">
			<img src="<?= $wwwUrl ?>/images/meals/<?= $oneModel['Photo']; ?>">
			<p><?= $oneModel['Name']; ?></p>
			<p><?= $oneModel['Description']; ?></p>
			<p><?= $oneModel['SalePrice']; ?></p>	
		</fieldset>
    </li>

<!--QUANTITE-->
    <li><label for="quantity">Quantité: </label>
    	<input type="number" name="quantity" value="1">  	
    </li>

<!--BOUTONS-->
    <button class="button-primary button" name="addproduct">Ajouter</button></a>

</ul>
</fieldset>

<!--BASKET-->

</fieldset>

<!--BOUTONS-->
    <input class="button-primary button" type="submit" name="" value="Valider la commande">
    <input class="button-cancel button" type="reset" name="" value="Annuler">