<!--RESERVETION TABLE-->

<form class="generic-form" method="post">
<h2><i class="fa fa-utensils"></i> Réservation d'une table</h2>

<!--INFORMATIONS-->
<fieldset>
    <legend><i class="fa fa-lock"></i> Informations </legend>

<ul>
    <!--Date-->
    <li><label for="booking">Date de réservation: </label>
        <select id="booking" name="jour" />

            <?php

            for ($i = 1; $i < 31; $i++)
            {
            echo '<option value=\'' . $i . '\'>' . $i . '</option>';
            }
            ?>  
     
        </select> /

        <select id="booking" name="mois" /> 
            <option value="01">Janvier</option>       
            <option value="02">Février</option>       
            <option value="03">Mars</option>       
            <option value="04">Avril</option>       
            <option value="05">Mai</option>       
            <option value="06">Juin</option>       
            <option value="07">Juillet</option>       
            <option value="08">Aout</option>       
            <option value="09">Septembre</option>       
            <option value="10">Octobre</option>       
            <option value="11">Novembre</option>       
            <option value="12">Decembre</option>  
        </select> /

        <select id="booking" name="year" /> 
     
            <?php

            for ($i = 2019; $i < 2025; $i++)
            {
            echo '<option value=\'' . $i . '\'>' . $i . '</option>';
            }
            ?>   
   
        </select> à 

        <select id="booking" name="heure" />

        	<option>11</option>
            <option>12</option>       
            <option>13</option>       
            <option>14</option>     
            <option>18</option>       
            <option>19</option>       
            <option>20</option>       
            <option>21</option>       
            <option>22</option>       
            <option>23</option>        
     
        </select> : 

        <select id="booking" name="minutes" />

        	<option>00</option> 
            <option>15</option>       
            <option>30</option>            
            <option>45</option>            
     
        </select>

    </li>
    <!--Nombre de places-->
    <li><label for="people">Nombre de personne: </label>
        <select id="people" name="people" />

            <?php

            for ($i = 1; $i < 12; $i++)
            {
            echo '<option value=\'' . $i . '\'>' . $i . '</option>';
            }
            ?>  
     
        </select></li>
</ul>

</fieldset>

<!--BOUTONS-->
    <input class="button-primary button" type="submit" name="réserver" value="Réserver">
    <input class="button-cancel button" type="reset" name="annuler" value="Annuler">

</form>