<!--CONNEXION-->

<form class="generic-form">
<h2><i class="fa fa-lock"></i> Se connecter avec un compte client</h2>

<!--AUTHENTIFICATION-->
<fieldset>
    <legend><i class="fa fa-lock"></i> Informations d'authenfication</legend>

<ul>
    <li><label for="mail">E-mail: </label><input type="email" id="mail" name="mail"></li>
    <li><label for="password">Mot de passe: </label><input type="password" id="password" name="password"></li>
</ul>

</fieldset>

<!--BOUTONS-->
    <input class="button-primary button" type="submit" name="" value="Créer le compte">
    <input class="button-cancel button" type="reset" name="" value="Annuler">

</form>